database {
  jdbcUrl = ""
  driver = "org.postgresql.Driver"
  migrationsLocation = "db/migration/postgres"
  user = ""
  password = ""
}

jwt {
  secret = ""
  issuer = "pcast-api"
  audience = "pcast-api"
  accessTokenExpireMinutes = 60
  refreshTokenExpireDays = 30
}
