database {
  jdbcUrl = ""
  driver = "org.postgresql.Driver"
  user = ""
  password = ""
}

jwt {
  secret = ${?JWT_SECRET}
  issuer = "pcast-api"
  audience = "pcast-api"
  accessTokenExpireMinutes = 60
  refreshTokenExpireDays = 30
}
